import { Metadata } from 'next';
import './globals.css';
import AuthSession from './_components/AuthSession';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
